/**
 * Enum que representa eventos associados ao modo de uma aplicação de modelagem específica.
 */
export default Object.freeze({
  CONCEPTUAL_SELECTION: 'CONCEPTUAL_SELECTION',
  CONCEPTUAL_ENTITY_INSERTION: 'CONCEPTUAL_ENTITY_INSERTION',
  CONCEPTUAL_RELATION_INSERTION: 'CONCEPTUAL_RELATION_INSERTION',
  CONCEPTUAL_ATTRIBUTE_INSERTION: 'CONCEPTUAL_ATTRIBUTE_INSERTION',
  CONCEPTUAL_GENERALIZATION_INSERTION: 'CONCEPTUAL_GENERALIZATION_INSERTION',
  LOGICAl_SELECTION: 'LOGICAl_SELECTION',
  LOGICAl_TABLE_INSERTION: 'LOGICAl_TABLE_INSERTION',
  CLEAR: 'CLEAR',
});