/**
 * Enum que representa os eventos da ferramenta de modelagem conceitual.
 */
export default Object.freeze({
  KEYBOARD_CLICK: 'KEYBOARD_CLICK',
  STAGE_CLICK: 'STAGE_CLICK',
  ENTITY_SELECT: 'ENTITY_SELECT',
  ENTITY_DOUBLE_CLICK: 'ENTITY_DOUBLE_CLICK',
  ENTITY_RESIZE: 'ENTITY_RESIZE',
  ENTITY_MOVE: 'ENTITY_MOVE',
  ATTRIBUTE_SELECT: 'ATTRIBUTE_SELECT',
  ATTRIBUTE_DOUBLE_CLICK: 'ATTRIBUTE_DOUBLE_CLICK',
  ATTRIBUTE_RESIZE: 'ATTRIBUTE_RESIZE',
  ATTRIBUTE_MOVE: 'ATTRIBUTE_MOVE',
  RELATION_SELECT: 'RELATION_SELECT',
  RELATION_DOUBLE_CLICK: 'RELATION_DOUBLE_CLICK',
  RELATION_RESIZE: 'RELATION_RESIZE',
  RELATION_MOVE: 'RELATION_MOVE',
  CONCEPTUAL_CARDINALITY_MOVE: 'CONCEPTUAL_CARDINALITY_MOVE',
  GENERALIZATION_SELECT: 'GENERALIZATION_SELECT',
  GENERALIZATION_DOUBLE_CLICK: 'GENERALIZATION_DOUBLE_CLICK',
  GENERALIZATION_RESIZE: 'GENERALIZATION_RESIZE',
  GENERALIZATION_MOVE: 'GENERALIZATION_MOVE',
  GENERALIZATION_TYPE_MOVE: 'GENERALIZATION_TYPE_MOVE',
  SEGMENT_START_MOVE: 'SEGMENT_START_MOVE',
  SEGMENT_END_MOVE: 'SEGMENT_END_MOVE',
});