/**
 * Enum que representa os eventos da ferramenta de modelagem lógica.
 */
export default Object.freeze({
  TABLE_SELECT: 'TABLE_SELECT',
  TABLE_DOUBLE_CLICK: 'TABLE_DOUBLE_CLICK',
  TABLE_MOVE: 'TABLE_MOVE',
  TABLE_RESIZE: 'TABLE_RESIZE',
  LOGICAL_CARDINALITY_MOVE: 'LOGICAL_CARDINALITY_MOVE',
  LOGICAL_KEYBOARD_CLICK: 'LOGICAL_KEYBOARD_CLICK',
  LOGICAL_STAGE_CLICK: 'LOGICAL_STAGE_CLICK',
});