/**
 * Enum que representa os eventos da ferramenta de modelagem lógica.
 */
export default Object.freeze({
  KEYBOARD_CLICK: 'KEYBOARD_CLICK',
  STAGE_CLICK: 'STAGE_CLICK',
  TABLE_SELECT: 'TABLE_SELECT',
  TABLE_DOUBLE_CLICK: 'TABLE_DOUBLE_CLICK',
  TABLE_MOVE: 'TABLE_MOVE',
  TABLE_RESIZE: 'TABLE_RESIZE',
  LOGICAL_CARDINALITY_MOVE: 'LOGICAL_CARDINALITY_MOVE',
  SEGMENT_START_MOVE: 'SEGMENT_START_MOVE',
  SEGMENT_END_MOVE: 'SEGMENT_END_MOVE',
});